# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "BGH Atlas"
email: bgh.atlas@gmail.com
description: "The Atlas is a top-level visual summary of end-member numerical models that the BGH is created."
# baseurl: ""
# url: "https://basin-genesis-hub.github.io/bgh_atlas/"

twitter_username: "EarthByteGroup"
github_username:  "basin-genesis-hub"
color_theme:  "#ff9d00"
color_text:  "#fff"
language:  "en"

logo: site_resources/BasinGensisHub.png

future: true
# exclude:  
#   - CHANGELOG.md
#   - CNAME
#   - Dockerfile
#   - Gemfile
#   - Gemfile.lock
#   - LICENSE
#   - README.md
#   - Vagrantfile

exclude: [vendor]

analytics: UA-143750223-1

jekyll_auth:
  ssl: true

# Build settings
markdown: kramdown
permalink: /:title/
plugins: [jekyll-paginate]
paginate: 5

# Plugins
plugins_dir:
  - jekyll-admin
  - jekyll-sitemap
